In [18]:
import torch
import numpy
import numpy as np
x = torch.empty(5,3)
b = torch.eye(5,3)
c = torch.randperm(10)
# print(b.add_(x))
# print(x.shape)
# print(b)
# print(c)
# y = x.view(15)
# z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
# print(x,x.size(),y, y.size(),z, z.size())

print('x:',x)
x_cp = x.clone().view(15)  #使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor。
x -= 1 
print('new_x:',x)
print("x_cp:",x_cp)

x: tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [7.2148e+22, 2.5226e-18, 6.4825e-10],
        [1.0072e-11, 3.0880e-09, 1.0504e-05],
        [4.1656e-11, 1.0503e-05, 2.9571e-18],
        [6.7333e+22, 1.7591e+22, 1.7184e+25]])
new_x: tensor([[-1.0000e+00, -1.0000e+00,  7.7052e+31],
        [ 7.2148e+22, -1.0000e+00, -1.0000e+00],
        [-1.0000e+00, -1.0000e+00, -9.9999e-01],
        [-1.0000e+00, -9.9999e-01, -1.0000e+00],
        [ 6.7333e+22,  1.7591e+22,  1.7184e+25]])
x_cp: tensor([0.0000e+00, 0.0000e+00, 7.7052e+31, 7.2148e+22, 2.5226e-18, 6.4825e-10,
        1.0072e-11, 3.0880e-09, 1.0504e-05, 4.1656e-11, 1.0503e-05, 2.9571e-18,
        6.7333e+22, 1.7591e+22, 1.7184e+25])


In [21]:
import torch
x = torch.randn(1)
print(x)
print(x.item())  #.item():, 它可以将一个标量Tensor转换成一个Python number

tensor([-0.6923])
-0.6923133730888367


In [22]:
“““
函数	                                功能
trace	                           对角线元素之和(矩阵的迹)
diag	                           对角线元素
triu/tril	                       矩阵的上三角/下三角，可指定偏移量
mm/bmm	                           矩阵乘法，batch的矩阵乘法
addmm/addbmm/addmv/addr/baddbmm..  矩阵运算
t	                               转置
dot/cross	                       内积/外积
inverse	                           求逆矩阵
svd	                               奇异值分解
”””

SyntaxError: invalid character in identifier (<ipython-input-22-684d901cf36e>, line 1)

In [23]:
# 广播机制
import torch
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)


tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [31]:
# #tensor 转 numpy
# a = torch.ones(5)
# b = a.numpy()
# print(a,b)
# a += 1
# print(a,b)
# b += 1
# print(a,b)

#numpy 转 tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)
a += 1
print(a,b)
b += 1
print(a,b)

c = torch.tensor(a)
print(c)
a += 1
print(a,c)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [53]:
#grad_fn 会返回通过运算得出的tensor的运算,初始tensor的grad_fn默认None
#requires_grad=True 相当于将tensor设计为leaf
import torch
x = torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn) #x为input值，None  leaf节点

y = x + 2
print(y)
print(y.grad_fn)

z = y*y*3
out = z.mean()
print(z,out)
print(x.is_leaf,y.is_leaf) #判定x y 是否为leaf节点

#requires_grad_() 来改变r_g属性默认false
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print('a:',a.requires_grad) #False
a.requires_grad_()  #默认改变，True
print('new_a:',a.requires_grad) #True
b = (a*a).sum()
print(b.grad_fn)

#梯度
out.backward()
print('out关于x的梯度：',x.grad)

out2 = x.sum()
out2.backward()
print('out2:',out2)
print('out2_grad:',x.grad)

out3 = x.sum()
print('out3:',out3)
x.grad.data.zero_()  #消除累计梯度
out3.backward()
print('out3_grad:',x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
True False
a: False
new_a: True
out关于x的梯度： tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
out2: tensor(4., grad_fn=<SumBackward0>)
out2_grad: tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
out3: tensor(4., grad_fn=<SumBackward0>)
out3_grad: tensor([[1., 1.],
        [1., 1.]])


In [57]:
#注意在y.backward()时，如果y是标量，则不需要为backward()传入任何参数；
#否则，需要传入一个与y同形的Tensor

import torch
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)  #现在 z 不是一个标量，所以在调用backward时需要传入一个
                #和z同形的权重向量进行加权求和得到一个标量。

v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)  #注:x.grad和x是同型张量
                #z对x的梯度
    
# torch.no_grad()  来中断梯度追踪

x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2 
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2

print(x.requires_grad)
print(y1, y1.requires_grad) # True
print(y2, y2.requires_grad) # False
print(y3, y3.requires_grad) # True

y3.backward()
print(x.grad)  #结果是‘2’，因为y2被隐藏排除梯度计算中，y3对x求梯度只计算了y2部分


tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)
tensor([2.0000, 0.2000, 0.0200, 0.0020])
True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True
tensor(2.)


In [65]:
#利用 tensor.data 来修改tensor值，并且不会被autograd记录从而影响反向传播

import torch
x = torch.ones(1,requires_grad=True)
print('x:\n',x)
print('x.data:\n',x.data) # 还是一个tensor
print('x.data的r_g值：\n',x.data.requires_grad) # 但是已经是独立于计算图之外

y = 2 * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播
print('y:\n',y)
y.backward()
print('修改x数据后的x：\n',x) # 更改data的值也会影响tensor的值
print('y对new_x的导数：\n',x.grad)

x:
 tensor([1.], requires_grad=True)
x.data:
 tensor([1.])
x.data的r_g值：
 False
y:
 tensor([2.], grad_fn=<MulBackward0>)
修改x数据后的x：
 tensor([100.], requires_grad=True)
y对new_x的导数：
 tensor([2.])
