In [1]:
#初始化模型参数
#在使用net前，我们需要初始化模型参数，如线性回归模型中的权重和偏差。
#PyTorch在init模块中提供了多种参数初始化方法。
#这里的init是initializer的缩写形式。
#我们通过init.normal_将权重参数每个元素初始化为随机采样于均值为0、
#标准差为0.01的正态分布。偏差会初始化为零。

from torch.nn import init

init.normal_(net[0].weight, mean=0, std=0.01)
init.constant_(net[0].bias, val=0)  # 也可以直接修改bias的data: net[0].bias.data.fill_(0)


NameError: name 'net' is not defined

In [8]:
%matplotlib inline
import torch
from IPython import display
from matplotlib import pyplot as plt
import numpy as np
import random


num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)), dtype=torch.float)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)


import torch.utils.data as Data

batch_size = 10
# 将训练数据的特征和标签组合
dataset = Data.TensorDataset(features, labels)
# 随机读取小批量
data_iter = Data.DataLoader(dataset, batch_size, shuffle=True)


for X, y in data_iter:
    print(X, y)
    break

    
class LinearNet(nn.Module):
    def __init__(self, n_feature):
        super(LinearNet, self).__init__()
        self.linear = nn.Linear(n_feature, 1)
    # forward 定义前向传播
    def forward(self, x):
        y = self.linear(x)
        return y

net = LinearNet(num_inputs)
print(net) # 使用print可以打印出网络的结构


for param in net.parameters():
    print(param)

    
    
from torch.nn import init

init.normal_(net.linear.weight, mean=0, std=0.01)
init.constant_(net.linear.bias, val=0)  # 也可以直接修改bias的data: net[0].bias.data.fill_(0)



loss = nn.MSELoss()


import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.03)
print(optimizer)

# 调整学习率
for param_group in optimizer.param_groups:
    param_group['lr'] *= 0.1 # 学习率为之前的0.1倍

    
#训练模型

num_epochs = 3
for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        output = net(X)
        l = loss(output, y.view(-1, 1))
        optimizer.zero_grad() # 梯度清零，等价于net.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d, loss: %f' % (epoch, l.item()))
    
    
#比较学到的参数和真实参数比较
dense = net.linear
print(true_w, dense.weight)
print(true_b, dense.bias)

    



tensor([[ 0.6114, -0.4682],
        [ 2.0767, -1.5415],
        [ 0.6945, -2.3197],
        [ 0.7082,  2.0623],
        [-0.4519,  0.5676],
        [-1.1885,  0.5403],
        [ 0.1600, -0.5103],
        [-0.0380,  0.0350],
        [ 0.5568, -0.9765],
        [-0.6657,  1.4053]]) tensor([ 7.0223, 13.5861, 13.4684, -1.3899,  1.3711, -0.0206,  6.2663,  4.0099,
         8.6506, -1.9106])
LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)
Parameter containing:
tensor([[-0.1685, -0.1861]], requires_grad=True)
Parameter containing:
tensor([-0.3472], requires_grad=True)
SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)
epoch 1, loss: 19.413059
epoch 2, loss: 3.374685
epoch 3, loss: 0.481478
[2, -3.4] Parameter containing:
tensor([[ 1.6799, -2.8557]], requires_grad=True)
4.2 Parameter containing:
tensor([3.5296], requires_grad=True)


In [13]:
##Fashion-MNIST 图像分类数据集

import torch
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import time
import sys
sys.path.append("/home/cxking/桌面/Dive-into-DL-pytorch/d2lzh_pytorch/utils.py") # 为了导入上层目录的d2lzh_pytorch
import utils as d2l

ModuleNotFoundError: No module named 'utils'

In [17]:
import sys
sys.path.append('/home/cxking/桌面/Dive-intu-pytorch/code/d2lzh_pytorch.zip')
import d2lzh_pytorch as d2l

ModuleNotFoundError: No module named 'd2lzh_pytorch'